language: node_js
node_js:
- '6'

before_install:
- openssl aes-256-cbc -K $encrypted_abf348a7c3b1_key -iv $encrypted_abf348a7c3b1_iv
  -in client-secret.json.enc -out client-secret.json -d

deploy:
  provider: gae
  keyfile: client-secret.json
  project: pam-server
